### ISSUE TITLE
1.19.3 Issue 

### ISSUE THREAD

**Issue by GordiNoki** [BlossomMods/BlossomHomes#4]
Hello there! I love your mods, but there is an issue running this mod on 1.19.3 version of fabric server.
```java
[18:06:01] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: field_25298
        at dev.codedsakura.blossom.homes.Home.toDestination(HomeController.java:60) ~[blossom-homes-2.0.5+1.19.jar:?]
        at dev.codedsakura.blossom.homes.BlossomHomes.lambda$runHome$2(BlossomHomes.java:172) ~[blossom-homes-2.0.5+1.19.jar:?]
        at dev.codedsakura.blossom.lib.teleport.TeleportUtils.lambda$teleport$4(TeleportUtils.java:260) ~[blossom-lib-2.5.0+1.19.jar:?]
        at dev.codedsakura.blossom.lib.teleport.TeleportUtils$1.handleZero(TeleportUtils.java:91) ~[blossom-lib-2.5.0+1.19.jar:?]
        at dev.codedsakura.blossom.lib.teleport.TeleportUtils$1.run(TeleportUtils.java:163) ~[blossom-lib-2.5.0+1.19.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.codedsakura.blossom.lib.teleport.TeleportUtils.tick(TeleportUtils.java:36) ~[blossom-lib-2.5.0+1.19.jar:?]
        at dev.codedsakura.blossom.lib.BlossomLib.lambda$onInitialize$1(BlossomLib.java:48) ~[blossom-lib-2.5.0+1.19.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-2.2.8+2894d6df85-93a78703a2fb6d26.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zco000$onEndTick(MinecraftServer.java:2844) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:868) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

As I understand it, this cryptic error means some problem with getting the current world dimension, probably this is due to the latest version of yarn. I hope you can fix it soon!

**Comment by CodedSakura** [comment]
fixed in cda154a6a5da667dd3410abc0abbbc26cbae27d1
